// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWbMtSskoxINbaQ-4CeutVN6oVjeSlww',
    appId: '1:412655392076:web:a7e67a2f6576d14926abe9',
    messagingSenderId: '412655392076',
    projectId: 'projectmobile-26b70',
    authDomain: 'projectmobile-26b70.firebaseapp.com',
    storageBucket: 'projectmobile-26b70.firebasestorage.app',
    measurementId: 'G-QQNYK0VCBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJS7-OKms6Rmj7Wv1jP50CBIS888SAEE',
    appId: '1:412655392076:android:f58159379b96aef926abe9',
    messagingSenderId: '412655392076',
    projectId: 'projectmobile-26b70',
    storageBucket: 'projectmobile-26b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP12QmmMFohLt2OYdvmjgkVLgM-TfjyJY',
    appId: '1:412655392076:ios:31dcee22ca66d27526abe9',
    messagingSenderId: '412655392076',
    projectId: 'projectmobile-26b70',
    storageBucket: 'projectmobile-26b70.firebasestorage.app',
    iosBundleId: 'com.example.goLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP12QmmMFohLt2OYdvmjgkVLgM-TfjyJY',
    appId: '1:412655392076:ios:31dcee22ca66d27526abe9',
    messagingSenderId: '412655392076',
    projectId: 'projectmobile-26b70',
    storageBucket: 'projectmobile-26b70.firebasestorage.app',
    iosBundleId: 'com.example.goLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjWbMtSskoxINbaQ-4CeutVN6oVjeSlww',
    appId: '1:412655392076:web:f41384317fd53de526abe9',
    messagingSenderId: '412655392076',
    projectId: 'projectmobile-26b70',
    authDomain: 'projectmobile-26b70.firebaseapp.com',
    storageBucket: 'projectmobile-26b70.firebasestorage.app',
    measurementId: 'G-2C31GTPGPS',
  );
}
